# Generated by Django 6.1.1 on 2026-09-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_age_customuser_height_customuser_neck_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default=0,
                max_length=6,
            ),
            preserve_default=False,
        ),
    ]
