# Generated by Django 6.1.1 on 2026-09-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="hip",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="neck",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="waist",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="weight",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
