# Generated by Django 6.1.1 on 2026-09-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_customuser_hip_alter_customuser_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="body_fat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lean_body_mass",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="hip",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="neck",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="waist",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
