# Generated by Django 6.1.1 on 2026-09-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_customuser_body_fat_customuser_lean_body_mass_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="weight_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slender", "Slender"),
                    ("excess weight", "Excess weight"),
                    ("obesity", "Obesity"),
                ],
                null=True,
            ),
        ),
    ]
