# Generated by Django 6.1.1 on 2026-10-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_customuser_weight_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="fitness_level",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                null=True,
            ),
        ),
    ]
