# Generated by Django 6.1.1 on 2026-10-07 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nutritionshapshot",
            old_name="basal_metabolic_rate",
            new_name="bmr",
        ),
        migrations.RenameField(
            model_name="nutritionshapshot",
            old_name="calorie_norm",
            new_name="calorie_norm_with_deficit",
        ),
    ]
